name: FLOW-JS-SDK Continuous Integration

on:
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      CLI_URL:
        description: "flow-cli artifact url"
        type: string

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Download flow-cli atrifact
        if: github.event.inputs.CLI_URL != ''
        run: >
          curl -L -o artifact.zip 
          -H "Accept: application/vnd.github+json" 
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
          -H "X-GitHub-Api-Version: 2022-11-28"
        # https://api.github.com/repos/onflow/devex-tests/actions/artifacts/479746403/zip
          ${{ github.event.inputs.CLI_URL }}

      - name: Unzip artifact
        if: github.event.inputs.CLI_URL != ''
        run: unzip -j -o artifact.zip

      - name: Copy flow binary 
        if: github.event.inputs.CLI_URL != ''
        run: |
          cp flow-x86_64-linux- /usr/local/bin/flow
          ls /usr/local/bin/flow
          flow version
      
      # if no beta flow-cli is provided, install official version 
      - name: Install released flow-cli
        if: github.event.inputs.CLI_URL == ''
        run: brew install flow-cli

      ### Run tests

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: make ci
