name: FLOW-JS-SDK Continuous Integration

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      # install flow CLI for integration testing
      - run: brew install flow-cli
      - run: make ci
